# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('director', models.CharField(max_length=20)),
                ('point', models.IntegerField()),
                ('count_point', models.IntegerField()),
            ],
        ),
    ]
