# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20170607_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Y',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie', models.ManyToManyField(to='show.Movie')),
            ],
        ),
    ]
